//
//  Model.swift
//  OnlineShop
//
//  Created by Anastasia N.  on 02.07.2025.
//

import Foundation
import FirebaseFirestore

struct Product: Identifiable, Codable, Hashable {
    @DocumentID var id: String?
    var name: String
    var description: String
    var image: String
    var price: Int
    
    enum CodingKeys: String, CodingKey {
        case id
        case name
        case description
        case image
        case price
    }
}

extension Product {
    
    static let allProducts: [Product] = [
        Product(name: "Dior Addict Lipstick", description: "Dior Addict is the Dior shine lipstick designed like a fashion accessory, with a formula now composed of 90%* natural-origin ingredients, housed in an ultra-couture and refillable case.\nIntense colour and shine with a vinyl effect, 24h** hydration and 6h*** wear, a formula infused with jasmine floral wax with hydrating properties: Dior Addict lipstick enhances the lips in bright and luminous shades with sensational shine. Among the palette of shades, Dior 8 stands out: a universal and addictive brick red inspired by the House of Dior's trendy and lucky number.\nIn its black vinyl lacquered case embossed with the Dior Oblique logo – an echo to the House's fashion creations – and topped with a silver pearl, the Dior Addict shine lipstick combines simplicity with elegance.\nRefillable, it slips into this timeless sleeve or one of the couture cases inspired by the Dior runway show designs each season: like a real wardrobe, the refillable lipstick case is available in Indigo Denim, Pink Cannage and Metallic Silver versions.\nAs part of the eco-design initiative led by Dior, the new shine lipstick icon is refillable to reduce its environmental impact. The black version uses some 34% less fossil fuels, 36% less greenhouse gases, and 47% less water**** to produce.\n* Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. The remaining ingredients contribute to the formula’s performance, sensory appeal and stability.\n** Instrumental test on 10 subjects.\n*** Clinical test on 25 subjects.\n**** Life cycle comparison of the packaging of 2 non-refillable Dior Addict lipsticks vs. 1 refillable Dior Addict lipstick and 1 refill.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw80a5e643/Y0291000/Y0291000_E000000148_E01_ZHC.jpg", price: 39),
        Product(name: "La Mousse OFF/ON Foaming Cleanser", description: "OFF/ON Foaming Cleanser, infused with purifying water lily cryoextract and niacinamide, reveals skin purity and clarity while providing care and protection in a luscious, creamy texture that transforms into a generous, airy foam. Daily skin cleansing becomes a true moment of care.\n> OFF:\n- Eliminates 99% of microparticles,¹ makeup and sunscreen residue.²\n> ON:\n- Strengthens the skin barrier for 24 hours²\n- Leaves skin hydrated for 6 hours,² protected and soothed\n- Skin appears more luminous, it is 42% smoother,³ and pores are tightened\n¹ Instrumental test on 30 women, tested on 1 µm, 20–25 µm, 49 µm.\n² Instrumental test on 30 women.\n³ Clinical tests on 40 people after 1 month of use.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw3d086a3c/Y0000013/Y0000013_E000000428_E01_ZHC.jpg", price: 48),
        Product(name: "Dior Backstage Glow Face Palette", description: "The iconic multi-use face makeup palette. The Dior Backstage Glow Face Palette is the Dior makeup artists' secret for adding instant radiance with professional results, from a natural healthy glow to an intense luminosity.\nFollowing the essential 001 Universal Neutrals, a palette with universal shades, and 002 Glitz, the harmony featuring intense, shimmering shades, Dior Backstage has created 3 new* makeup palettes. Each palette features four shades with gold tones to create a multitude of makeup looks and finishes that suit all skin tones:\n- Pure Gold revisits yellow gold in its pure form: yellow gold and platinum gold shades with a metallic finish, pure gold shades with an intense finish, and warm gold with a shimmery finish.\n- Rose Gold illustrates gold infused with a rosy gleam: pearly pink and pure pink shades with an intense finish, rose gold and golden peach shades with a metallic finish.\n- Copper Gold incarnates gold with warm copper tones: a coral with a glittery finish, copper shades with a metallic finish, bronze with a shimmery finish and golden bronze with an intense finish.\n* At Dior.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw3e6be695/Y0015002/Y0015002_C044400001_E01_ZHC.jpg", price: 43),
        Product(name: "Dior Forever Nude Bronze - large format", description: "Summer on your skin in a single sweep: Dior Forever Nude Bronze warms the complexion with a matte sun-kissed effect in a streak-free finish. This “summer-proof”¹ powder bronzer is your longwearing summer makeup ally. Dior Forever Nude Bronze contains the essence of the “Tan Beautifier” complex, infused with hyaluronic acid and a vitamin C derivative for a summer tan that lasts.\n- FINISH: matte finish\n- WEAR: longwearing\n- COVERAGE: buildable\n- SKINCARE: contains the essence of the “Tan Beautifier” complex\n- SHADES: 4 shades\n¹ Wear in conditions of heat and humidity.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw88cc846b/Y0000037/Y0000037_E000000098_E01_ZHC.jpg", price: 65),
        Product(name: "Dior Addict Lip Glow Oil", description: "The Dior Addict Lip Glow lip balm is available as a glossy lip oil that deeply protects and enhances the lips, bringing out their natural colour.\nGenuine lip care infused with cherry oil, Dior Addict Lip Glow Oil instantly nourishes, protects, softens and revitalises the lips.\nThis lip oil combines an intense lip care formula with a natural, flattering colour finish for an ultra-luminous result. Dior Addict Lip Glow Oil adapts to all lip colours to bring out their rosy glow. Its non-greasy, non-sticky oil texture pushes the boundaries of shine and creates a smoothing film that shapes the lips with an almost magnifying mirror-shine effect.\nMulti-use, Dior Addict Lip Glow Oil can be worn equally well on its own, as a primer under lipstick, or as a top coat for volumising shine.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw35e7386a/Y0124000/Y0124000_E000000382_E01_ZHC.jpg", price: 33),
        Product(name: "Dior Backstage Rosy Glow Stick", description: "Complete your glow routine with an exclusive Glow Makeup Trio by clicking here, designed for a radiant, rosy pink glow.\nThe Dior blush stick offers 12 hours¹ of \"custom\" colour and a dewy-glow finish that reflects light, for cheekbones that appear enhanced and plumped. Powered by a unique technology², each shade reacts to the skin's pH and takes on cool pink or warm coral undertones.\nMoisturising and comfortable, the creamy texture of the Rosy Glow blush stick blends seamlessly with the skin for a bare-skin effect for a clean look.\n- SHADES: 7 shades that adapt to skin's pH for a \"custom\" makeup result\n- FINISHES: 2 dewy-glow finishes, radiant and pearlescent\n- COVERAGE: buildable, for natural to intense looks\n- TEXTURE: smooth and easy to blend\n- CARE: 12 hours of hydration³ and comfortable wear powered by a formula infused with cherry oil\n¹ Instrumental test on 25 women.\n² At Dior.\n³ Instrumental test on 30 subjects.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw939ef2ef/Y0000048/Y0000048_E000000453_E01_ZHC.jpg", price: 37),
        Product(name: "Miss Dior Eau de Parfum", description: "In 1947, Miss Dior was born out of a wild impetus where the pressing desire to re-enchant the lives of women and open up their eyes, once again, to the sparkling colours of love was felt. Following a bleak period, at that time this scent was synonymous with renewed happiness, poetry, and harmony for Christian Dior. Miss Dior intrigues, excites and invites us to marvel at love and all the beauty in the world.\nEchoing its inspiring character, the Miss Dior fragrance is like an olfactory “millefiori”. Centifolia Rose, with its honeyed and peppery notes, reigns over a delectably creamy velvet heart. It is embroidered with fresh Lily-of-the-Valley notes, an apricot-tinged Peony accord, and powdery Iris notes. Miss Dior is thus built around an elegant, striking bouquet—like a “millefiori” that seems to carry countless flowers in endless colours. At the base, slight notes of tender wood envelop the composition.\nThe couturier's fragrance, Miss Dior eau de parfum, is adorned with a signature silver-coloured poignard fabric bow—a few centimeters of pure luxury is tied around the bottle's neck to match its silvery fabric-effect label. Beneath the bottle, the emblematic Miss Dior houndstooth motif is engraved in the glass.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw15a3598c/Y0996347/Y0996347_C099600764_E01_ZHC.jpg", price: 145),
        Product(name: "Dior Solar The Sublimating Oil", description: "Dior Solar The Sublimating Oil is a sparkling dry oil for face, body and hair that enhances them all year round with the characteristic glow of a warm, sunny summer.\nAfter application, the oil embellishes skin with a radiant glow: thanks to its pearly, sparkling texture, skin is noticeably more beautiful and the tan is enhanced with each application. Skin glows as if it has been smoothed and nourished.\nUsed on the lengths and ends of the hair, Dior Solar The Sublimating Oil gives a feeling of hydration and a pearly effect, while adding a radiant light.\nThis sumptuous Dior oil is formulated with 95%* natural-origin ingredients and offers a highly appealing texture that spreads over the skin with a pleasant monoi fragrance.\nShake before use.\n* Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. Water percentage included. The remaining 5% contribute to the formula’s performance, sensory appeal and stability.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwf5eeb1af/Y0997055/Y0997055_C099700258_E01_ZHC.jpg", price: 50),
        Product(name: "Dior Backstage Rosy Glow", description: "Complete your glow routine with an exclusive Glow Makeup Trio by clicking here, designed for a radiant, rosy pink glow.\nThe iconic Dior blush offers long-wearing, buildable, \"custom\" colour powered by a formula featuring a technology that reacts to the skin's pH to create a personalised colour.\nRosy Glow gives skin an instant healthy glow and is now even more buildable powered by a formula concentrated in pigments. Ultra-fine, lightweight, the blush blends seamlessly with the skin for a touch of natural colour with a weightless, second-skin result.\n- SHADES: 7 shades that adapt to skin's pH for a \"custom\" makeup result\n- FINISHES: 2 finishes, natural blur and pearly\n- COVERAGE: buildable\n- TEXTURE: soft, fine powder", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwc3be0906/Y0000049/Y0000049_E000000573_E01_ZHC.jpg", price: 35),
        Product(name: "Dior Addict Lip Glow Butter", description: "Elevate your lip care ritual with our exclusive 4-piece Lip Glow Butter collection by clicking here, designed to unveil the most juicy, healthy glow.\nDior Addict Lip Glow Butter is the high-shine treatment infused with a peptide and ceramide duo to instantly enhance the lips’ appearance. Made from 90% ingredients of natural origin¹, its formula strikes the perfect balance between a balm and a gloss. It provides 24 hours² of deep hydration and adds a touch of colour and shine for radiant lips and a natural look.\nRich and enveloping, its buttery texture visibly smooths and plumps the lips for 24 hours.³ Its intensely comfortable formula offers a soothing sensation for 8 hours.⁴ The applicator hugs the shape of the lips for a pillow-soft sensation.\n- SHADES: 5 juicy shades\n- FINISHES: high-shine, glossy or pearlescent\n- TEXTURE: rich and soothing\n- SKINCARE: formula infused with a peptide and ceramide duo to support the skin barrier for 24 hours³\n¹ Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. The remaining ingredients contribute to the formula’s performance, sensory appeal and stability.\n² Instrumental test on 30 women.\n³ Instrumental test on 30 subjects.\n⁴ Self-scoring test on 30 women.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwf6c176a8/Y0000050/Y0000050_E000000588_E01_ZHC.jpg", price: 33),
        Product(name: "Dior Forever Glow Luminizer", description: "Dior Forever reinvents its luminous glow powder available in 3 new finishes¹ to reflect light from all angles: Halo for a crystal glow, Strobe² for a duochrome shimmer, and Sequin for sparkling radiance.\nThis unique formula¹ boasts a concentration of pearlescent micro-pigments with subtle shine in a clear gel base. It blends seamlessly with the skin and diffuses light in its purest intensity.¹\n- FINISHES: Halo, Strobe and Sequin\n- WEAR: longwearing\n- TEXTURE: shimmering pearlescent pigment-in-gel technology with a barely-there feel\n- SKINCARE: infused with hyaluronic acid to maintain hydration of the skin\n- SHADES: 7 shades\nA glow powder that clips into a silver couture case adorned with the initials “CD” for Christian Dior.\n¹ At Dior.\n² Stroboscopic effect.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwa5a657db/Y0000010/Y0000010_E000000091_E01_ZHC.jpg", price: 48),
        Product(name: "Dior Homme Intense", description: "Dior Homme is worn the way you wear an elegantly sharp, modern suit. Dior Homme Intense Eau de Parfum reveals the extreme grandeur and sophistication of a generous and powerful eau de parfum. The olfactory intensity of Iris is enhanced by a sensual Ambery facet and precious Wood base. A scented, sensual script whose trail calls to you.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw0c433874/Y0479201/Y0479201_F047924709_E01_ZHC.jpg", price: 118),
        Product(name: "Diorshow Maximizer 4D", description: "The icon of Dior eye makeup, Diorshow Maximizer 4D lash primer-serum improves mascara performance by heightening its radiance and colour. It takes action in 4 dimensions: volume, curl, length and definition, for lashes that appear oversized, immediately and for 24h*.\nComposed with a skincare formula infused with floral extracts, this lash primer boasts a balm texture that coats lashes in a both dense and airy film, and improves lash appearance day after day. Lashes appear nourished, revitalised and fortified, visibly longer, smoother and suppler. Diorshow Maximizer 4D can also be applied on its own at night as a lash conditioner.\nIts oblique brush is able to deliver just the right amount of product to create fuller, curled and fanned lashes for a spectacular wide-eyed look.\n* Instrumental test on 25 subjects.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwd05e652e/Y0997170/Y0997170_C099700798_E01_ZHC.jpg", price: 35),
        Product(name: "Dior Prestige La Micro-Huile de Rose Activated Serum", description: "An anti-ageing serum for face and neck, Dior Prestige La Micro-Huile de Rose Activated Serum is the ultimate Dior micro-nutritive supplement for visibly younger, plumper skin.\nIts Nutri-Rosapeptide-infused formula helps tired skin that is losing the appearance of elasticity and radiance to recover faster: it is 6 times more concentrated¹ in 22 micro-nutrients from the Rose de Granville, infused with an oily extract that is 14 times richer² in correcting omegas and enriched with plumping hyaluronic acid. Essential for promoting the recovery mechanisms that give skin a youthful, plump appearance, omegas are carefully protected within the 10,000 micro-pearls.³\nSkin glows with a healthy look and recovers from aggressions twice as quickly⁴ , appearing 3 times plumper⁵ with a visible wrinkle reduction multiplied by 3.⁶ It looks firmer, plumper and more luminous, with a smoother texture.\nFor the 1st time, the serum’s effectiveness has been tested after laser:⁷ skin barrier strength return to inital level in 3 days, and it supports its visible anti-aging benefits.⁸\n¹ In the new formula compared to the original La Micro-Huile de Rose formula (2017).\n² In the new oily extract compared to the 2020 oily extract.\n³ In a 30 ml bottle.\n⁴ Instrumental test on 30 women, compared to recovery without using La Micro-Huile de Rose Activated Serum.\n⁵ Clinical assessment by a dermatologist on 30 women in Japan. Comparison between immediate application and after one month of use.\n⁶ Clinical assessment by a dermatologist on 30 women in China. Comparison between the effect after one week of use and the effect after one month of use.\n⁷ Non-invasive laser.\n⁸ Clinical assessment of La Micro-Huile de Rose group efficacy on the anti-aging efficacy compared to placebo group.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw0fd304d1/Y0997186/Y0997186_C099700025_E01_ZHC.jpg", price: 290),
        Product(name: "Dior Forever Skin Correct", description: "Dior Forever Skin Correct is the clean* high-perfection concealer by Dior that offers 24h** wear and hydration.\nIn a single sweep, this multi-use, full-coverage complexion concealer with a creamy texture hides undereye circles, localized redness, pigment spots and blemishes for flawless correcting and undereye circle concealing action with no transfer. From morning to night, it smooths the complexion and enhances the skin, without settling into facial lines. It stands up in all conditions of heat and humidity.***\nComposed of 96%**** natural-origin ingredients, this concealer is clean,* formulated according to a rigorous list of ingredients and infused with iris extract with hydrating properties, wild pansy extract that contributes to comfort and yarrow extract that contributes to the brightening and smoothing action in the eye area.\nThis concealer is non-comedogenic and dermatologically tested.\n* For more information, visit the Dior page “Our Commitments.”\n** Wear: instrumental test on 27 subjects. Hydration: instrumental test on 31 subjects.\n*** Instrumental test by image analysis (27 women). 5 cycles of 10 minutes in conditions of heat and humidity (temperature 30-33°C and hygrometry 70%-75% HR [relative humidity]).\n**** Amount calculated based on the ISO 16128-1 and ISO 16128-2 standard. Water percentage included. The remaining ingredients contribute to the formula’s performance, sensory appeal and stability.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw6f8d5705/Y0326000/Y0326000_C032600010_E01_ZHC.jpg", price: 34),
        Product(name: "Diorshow Overvolume", description: "Diorshow Overvolume: the mascara that combines extreme volume and lash-by-lash definition.\nThis mascara instantly provides a +440%* extreme volume boost combined with lash-by-lash definition for a fanned-out look. Intensely pigmented, it coats the lashes in a deep, no-transfer shade of black that lasts 24 hours.*\nThe case of this Dior mascara is adorned with cannage, the iconic couture code of the House.\n- FINISH: +440%* extreme volume boost and clump-free, lash-by-lash definition\n- SHADE: high-intensity black\n- WEAR: 24 hours,* no-transfer\n- LASH CARE: D-Panthenol helps to revitalize and strengthen lashes\n* Instrumental test on 30 subjects.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw6ebf6449/Y0000002/Y0000002_E000000243_E01_ZHC.jpg", price: 35),
        Product(name: "Dior Backstage Eye Palette", description: "Designed by Peter Philips, Creative and Image Director for Dior Makeup, the Dior Backstage Eye Palette is the Dior makeup artists' secret weapon for achieving makeup looks from the most natural to the most intense, while ensuring a long-wear finish.\nInspired by the energy backstage at the Dior runway shows, this makeup palette combines 9 ultra-pigmented, easy-to-blend eyeshadows with matte, pearlescent, metallic, holographic and glittery finishes. Each harmony is the interpretation of a colour theme, available in complementary shades to achieve a multitude of looks.\nTo apply the eyeshadows with a brush, use a Dior Backstage eyeshadow brush: shader brush No. 21 or blending brush No. 22 or No. 23.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dw45039f13/Y0012000/Y0012000_C038300002_E01_ZHC.jpg", price: 45),
        Product(name: "Dior Forever Skin Perfect", description: "Dior has created a multi-use foundation stick with a natural, blurred finish that provides 24h wear¹ and hydration.² Its buildable coverage evens out the complexion and erases imperfections to reveal a flawless complexion in a single step.\nTrue skincare in a stick, Dior Forever Skin Perfect lets the skin breathe and provides continuous hydration. Its soft, lightweight texture was developed to melt into the skin, blending seamlessly without any effort for a barely-there feel and 24h of comfort.³\nEnriched with pigments, it visibly reduces the appearance of pores and conceals imperfections. This foundation stick delivers a perfect \"blurring filter\" effect with heat- and humidity-resistant wear.\nMulti-use, it can be applied as foundation over the entire face, used as a targeted concealer, or kept close at hand for touch-ups on the go.\nNon-comedogenic. Dermatologically tested.\n¹ Instrumental test on 25 subjects.\n² Instrumental test on 33 subjects.\n³ Self-rating by 25 subjects.", image: "https://www.dior.com/dw/image/v2/BGXS_PRD/on/demandware.static/-/Sites-master_dior/default/dwb35e9244/Y0379000/Y0379000_C037900025_E01_ZHC.jpg", price: 48)
    ]
    
    static func uploadAllProducts() {
        for product in Product.allProducts {
            do {
                _ = try FB.productsCollection.addDocument(from: product)
            } catch {
                print("Ошибка при добавлении продукта: \(error)")
            }
        }
    }
}
